import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        'background-secondary': 'var(--background-secondary)',
        foreground: 'var(--foreground)',
        'foreground-secondary': 'var(--foreground-secondary)',
        'foreground-muted': 'var(--foreground-muted)',
        'foreground-subtle': 'var(--foreground-subtle)',
        surface: 'var(--surface)',
        'surface-strong': 'var(--surface-strong)',
        'surface-soft': 'var(--surface-soft)',
        'surface-nav': 'var(--surface-nav)',
        'surface-footer': 'var(--surface-footer)',
        'surface-raised': 'var(--surface-raised)',
        'surface-inverse': 'var(--surface-inverse)',
        'surface-media': 'var(--surface-media)',
        'surface-ring': 'var(--surface-ring)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-muted': 'var(--border-muted)',
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-strong': 'var(--primary-strong)',
        'primary-foreground': 'var(--primary-foreground)',
        'primary-border': 'var(--primary-border)',
        'primary-glow': 'var(--primary-glow)',
        'primary-soft': 'var(--primary-soft)',
        'primary-muted': 'var(--primary-muted)',
        'status-danger-surface': 'var(--status-danger-surface)',
        'status-danger-foreground': 'var(--status-danger-foreground)',
        overlay: 'var(--overlay)',
        'overlay-wide': 'var(--overlay-wide)',
      },
      boxShadow: {
        nav: 'var(--shadow-nav)',
        brand: 'var(--shadow-brand)',
        card: 'var(--shadow-card)',
        panel: 'var(--shadow-panel)',
        'icon-panel': 'var(--shadow-icon-panel)',
        button: 'var(--shadow-button)',
        toggle: 'var(--shadow-toggle)',
        'toggle-active': 'var(--shadow-toggle-active)',
        'toggle-inverse-active': 'var(--shadow-toggle-inverse-active)',
      },
      letterSpacing: {
        nav: 'var(--tracking-nav)',
        subtle: 'var(--tracking-subtle)',
        caps: 'var(--tracking-caps)',
        metric: 'var(--tracking-metric)',
        title: 'var(--tracking-title)',
      },
    },
  },
}
